name: Invision DSM configuration
description: "Create a DSM configuration file"
author: "Alexandrshy"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "package"
  color: "black"
inputs:
  token:
    description: "Authentication token"
    required: true
  organization:
    description: "The name of the DSM organization"
    required: true
  dsmHost:
    description: "The URL to which the Storybook will be uploaded"
    required: false
    default: "projects.invisionapp.com"
  outputDir:
    description: "Builds the output folder path"
    required: false
    default: ".dsm"
  storyPath:
    description: "A glob pattern of where DSM should search for stories"
    required: false
    default: "src/**/*.stories.js"
  filePath:
    description: "The path to the location of the configuration file"
    required: false
    default: ""
  fileName:
    description: "The file name"
    required: false
    default: ".dsmrc"
