name: Invision DSM configuration
description: "Create a DSM configuration file"
author: "Alexandrshy"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "package"
  color: "black"
inputs:
  token:
    description: "Authentication token"
    required: true
